Upgrade sonar_scanner_cli_version to 5.0.2 to add support for newer java versions
Currently when Java 21 is used, the error is displayed:

    Error: LinkageError occurred while loading main class org.sonarsource.scanner.cli.Main
        java.lang.UnsupportedClassVersionError: org/sonarsource/scanner/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

This commit upgrades sonar_scanner_cli version and add
support for newer version of Java.